openapi: 3.0.0
info:
  title: Modello Dati - Scheda A2_29 - Scheda relativa all'aggiudicazione sottosoglia senza invio al TED.
  version: 1.0.0
components:
  schemas:
    AppaltoA2_29Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA1_29Type'
      type: object
      additionalProperties: false
      properties: 
        datiBaseProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraCompletoType'
        datiBaseStrumentiProcedura:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseStrumentiProceduraAType' 
        datiBaseSubappalti:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSubappaltiRequiredType' 
    AggiudicazioneA2_29Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneCompletaType'
      type: object
      additionalProperties: false
      properties:   
        datiBaseRisultatoProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseEsitoRisultatoProceduraType'
        datiBaseAggiudicazioneAppalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoType'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType' 
        datiBaseSottomissioniRicevute:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSottomissioniRicevuteType'          
    AnacFormA2_29Type:
      description: Contiene tutti i dati relativi all'aggiudicazione
      type: object
      additionalProperties: false
      required: [appalto,aggiudicazioni]
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoA2_29Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneA2_29Type'       
    SchedaA2_29Type:
      description: Avviso aggiudicazione direttiva generale, regime ordinario. Articolo 50 comma 9 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA2_29Type'          