openapi: 3.0.0
info:
  title: Modello Dati - Scheda P1.20 - Scheda di pubblicazione avviso per un bando di gara sopra la soglia europea e sotto soglia con invio al TED dell'eform20.
  version: 1.0.0
components:
  schemas:
    AnacFormP1.20Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale di un bando di gara soprasoglia 
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'   
      type: object
      required: [categoria, finanziamenti, opzioni/rinnovi, appalto,lotti]
      additionalProperties: false
      properties:  
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP.20Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP.20Type' 
    SchedaP1.20Type:
      description: Scheda di pubblicazione avviso per un bando di gara sopra la soglia europea e sotto soglia con invio al TED dell'eform20.
      type: object
      required: [anacForm, eform,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP1.20Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'  
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'          
         