openapi: 3.0.0
info:
  title: Modello Dati - Scheda P2_24 - Scheda di pubblicazione avviso per un bando di gara sottosoglia. 
  version: 1.0.0
components:
  schemas:
    AppaltoP2_24Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP_24Type'     
      type: object
      additionalProperties: false
      required: [datiBase,datiBaseProcedura]
      properties:   
        datiBase:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoType'
        datiBaseProcedura:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraType'              
    LottoP2_24Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP_24Type'      
      type: object
      additionalProperties: false
      required: [datiBase,datiBaseDocumenti,datiBaseTerminiInvio]
      properties:  
        datiBase:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoType' 
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoType' 
        datiBaseAggiudicazione:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneOptionalType'
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType' 
        datiBaseImporto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseImportoType'  
        datiBaseCPV:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'   
        datiBaseDocumenti:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDocumentiType'           
    AnacFormP2_24Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale.
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      type: object
      additionalProperties: false
      required: [appalto,lotti]
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoP2_24Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP2_24Type'
    SchedaP2_24Type:
      description: Avviso di concorso di progettazione - settori speciali. Articolo 46 decreto legislativo 36/2023.
      type: object
      required: [anacForm,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP2_24Type'          
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         
