openapi: 3.0.0
info:
  title: Modello Dati - Scheda P1_17 - Scheda di pubblicazione avviso per un bando di gara sopra la soglia europea e sotto soglia con invio al TED dell'eform17.
  version: 1.0.0
components:
  schemas:
    AnacFormP1_17Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale.
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'   
      type: object
      additionalProperties: false
      required: [appalto,lotti]
      properties:      
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP_17Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP_17Type'    
    SchedaP1_17Type:
      description: Bando di gara — direttiva settoriale, regime ordinario. Articolo 69 della direttiva 2014/25/UE. Articolo 155 comma 3 lettera c)  decreto legislativo 36/2023. Articolo 163 decreto legislativo 36/2023. Articolo 164 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP1_17Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'  
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         