openapi: 3.0.0
info:
  title: Modello Dati - Scheda ISDA1 - Istituzione Sistema Dinamico di Acquisizione Sopra soglia.
  version: 1.0.0
components:
  schemas:   
    AnacFormISDA1_Type:
      allOf: # estende la classe AnacFormBaseType
        - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType' 
      type: object
      required: [appalto,lotti]
      additionalProperties: false
      properties:  
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoISDABaseType'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoISDABaseType'  
    SchedaISDA1Type:
      description: Istituzione Sistema Dinamico di Acquisizione Sopra soglia. Articolo 32 comma 2, 6 decreto legislativo 36/2023.
      type: object
      required: [anacForm,eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormISDA1_Type'        
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'         
