openapi: 3.0.0
info:
  title: Modello Dati - Scheda P1.15 - Scheda di pubblicazione avviso sull'esistenza di un sistema di qualificazione, con invio al TED dell'eform15.
  version: 1.0.0
components:
  schemas:
    AppaltoP.15Type:
      description: Oggetto che riporta i dati dell'appalto 
      type: object
      additionalProperties: false
    LottoP.15Type:
      description: Oggetto che riporta i dati del lotto
      type: object
      additionalProperties: false
    AnacFormP1.15Type:
      description: Contiene tutti i dati necessari per la pubblicazione di un avviso sull'esistenza di un sistema di qualificazione. 
      type: object
      additionalProperties: false
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoP.15Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP.15Type'
    SchedaP1.15Type:
      description: Scheda di pubblicazione avviso sull'esistenza di un sistema di qualificazione, con invio al TED dell'eform15. 
      type: object
      required: [anacFormP1, eform]
      additionalProperties: false
      properties:
        anacFormP1:
          $ref: '#/components/schemas/AnacFormP1.15Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'        