openapi: 3.0.0
info:
  title: Modello Dati - Scheda SE - Elenco richieste di adesione elenco fornitori
  description: | 
    L'operazione di Inserimento pone in stato "In Valutazione" il partecipante nel caso di nuovo partecipante o di partecipante precedentemente cancellato. \
    L'operazione di Conferma pone in stato "Iscritto" il partecipante nel caso di partecipante con stato "In valutazione" o in stato "Cancellato", e permette l'inserimento diretto di un nuovo partecipante in stato "Iscritto". \
    L'operazione di Rivalutazione pone in stato "In Valutazione" il partecipante con stato "Iscritto". \
    L'operazione di Modifica è possibile per partecipanti in stato "In valutazione" o "Iscritto", lasciando inalterato lo stato del partecipante. \
    L'operazione di Cancellazione è possibile per partecipanti in stato "In valutazione" o "Iscritto", e pone lo stato del partecipante in "Cancellato".
  version: 1.0.0
components:
  schemas:
    PartecipanteSEType:
      type: object
      required: [partecipante, operazione] 
      additionalProperties: false
      properties:
        partecipante:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/PartecipanteType'
        operazione:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/OperazioneElencoEnum' 
    SchedaSEType:
      description: Richieste di adesione elenco fornitori.
      type: object
      additionalProperties: false
      required: [anacForm]
      properties:
        anacForm:
          type: object
          additionalProperties: false
          required: [idElenco,partecipanti,lotIdentifier]
          properties:
            idElenco:
              description: id restituito dal servizio all'invio della scheda elenco fornitori
              type: string
            lotIdentifier:
              description: Id univoco del lotto generato dalla stazione appaltante - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-137 - Purpose Lot Identifier del TED
              type: string
            partecipanti:
              description: Dati relativi ai partecipanti all'elenco
              type: array
              items:
                $ref: '#/components/schemas/PartecipanteSEType'
                       