openapi: 3.0.0
info:
  title: Modello Dati - Scheda A2_34 - Scheda relativa all'aggiudicazione sottosoglia senza invio al TED.
  version: 1.0.0
components:
  schemas:
    AppaltoA2_34Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA1_34Type'
      type: object
      additionalProperties: false
      properties: 
        datiBaseProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraAType' 
        datiBaseSubappalti:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSubappaltiType'          
    AggiudicazioneA2_34Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneCompletaType'
      type: object
      additionalProperties: false
      properties:
        datiBaseSottomissioniRicevute:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSottomissioniRicevuteType'      
        datiBaseRisultatoProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseEsitoRisultatoProceduraType'
        datiBaseAggiudicazioneAppalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoType'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'      
    AnacFormA2_34Type:
      description: Contiene tutti i dati relativi all'aggiudicazione.
      type: object
      required: [appalto,aggiudicazioni]
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoA2_34Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneA2_34Type'  
    SchedaA2_34Type:
      description: Avviso di aggiudicazione di un appalto, direttiva settoriale, regime allegerito. Articolo 50 comma 9 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA2_34Type'