openapi: 3.0.0
info:
  title: Modello Dati - Scheda A3.6 - Scheda di aggiudicazione relativa ad affidamento a soc. inhouse
  version: 1.0.0
components:
  schemas:
    AppaltoA3.6Type:
      type: object
      additionalProperties: false
      required: [relazioneUnicaSulleProcedure,preinformazione,termineRidottoAvvisoPreinformazione]      
      properties: 
        relazioneUnicaSulleProcedure:
          description: Il sottoscritto dichiara che questa SA ha redatto la Relazione Unica sulle Procedure
          type: boolean        
        preinformazione:
          description: E' stata effettuata la preinformazione?
          type: boolean
        termineRidottoAvvisoPreinformazione:
          description: E' stato utilizzato un termine ridotto con avviso di preinformazione?
          type: boolean             
    AggiudicazioneA3.6Type:
      description: Oggetto che riporta i dati inerenti la fase di aggiudicazione
      type: object
      additionalProperties: false
      required: [lotIdentifier,afferenteInvestimentiPNRR]
      properties: 
        cig:
          description: codice identificativo lotto
          type: string
          example: 
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string   
        afferenteInvestimentiPNRR:
          description: L’appalto o concessione è afferente gli investimenti pubblici finanziati, in tutto o in parte, con le risorse previste dal PNRR (Piano Nazionale di Ripresa e Resilienza) e/o dal PNC (Piano nazionale per gli investimenti complementari)?
          type: boolean  
        cupLotto:
          description: Cup associati al lotto
          type: array
          items: 
            type: string 
        paritaDiGenereGenerazionale:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ParitaDiGenereGenerazionaleType'          
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoType'          
        offertePresentate:
          description: Dati degli aggiudicatari
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/OfferteType' 
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'
        datiBaseAggiudicazioneAppalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoType'              
    AnacFormA3.6Type:
      description: Contiene tutti i dati relativi alle Società in-house.
      type: object
      required: [appalto,aggiudicazioni]
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoA3.6Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneA3.6Type'      
    SchedaA3.6Type:
      description: Scheda di aggiudicazione relativa alle Società in-house
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA3.6Type' 
