openapi: 3.0.0
info:
  title: Modello Dati - Scheda ID - Scheda  per l'integrazione dei dati non essenziali ai fini della pubblicità legale e del flusso della procedura.
  description: | 
    In caso di modifica dei cup la scheda dovrà contenere ogni volta la lista dei cup validi. Questa lista sovrascriverà la precedente lista inviata.\
    Quindi i cup validi saranno sempre solo quelli inviati con l'ultima scheda ID.\
    La scheda permette la modifica del ribasso di aggiudicazione solo in caso di omessa comunicazione in fase di affidamento.\
    Con questa scheda può essere comunicata anche l'informazione relativa al docFAP, ovvero se è stato realizzato e autorizzato entro i termini lo studio di fattibilità che esenta dall'uso del BIM.\
    La scheda permette infine di modificare l'indirizzo dei documenti di gara    
  version: 1.0.0
components:
  schemas:
    ComunicazioneCUPType:
      description: Dati inerenti la modifica del CUP
      type: object
      required: [motivoVariazioneCUP,cup]
      additionalProperties: false
      properties:
        motivoVariazioneCUP:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoVariazioneCUPEnum'    
        cup:
          description: Cup
          type: array
          items:
            type: string
            pattern: ^[a-zA-Z0-9]{15}$
    ComunicazioneRibassoAggiudicazioneType:
      description: Dati inerenti la comunicazione del ribasso di aggiudicazione
      type: object
      required: [idPartecipante, motivoCorrezione,ribassoAggiudicazione]
      additionalProperties: false
      properties:
        idPartecipante: 
          description: id partecipante
          type: string  
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"   
        motivoCorrezione:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoCorrezioneEnum'    
        ribassoAggiudicazione:
          description: ribasso di aggiudicazione. valori ammessi-> (x<100); sono ammessi valori negativi. I valori positivi saranno considerati come integrazione del campo offertePresentate.offertaEconomica, mentre i valori negativi andranno ad integrare il campo offertePresentate.offertaInAumento.
          type: number
          format: double
          maximum: 100
          exclusiveMaximum: true
    ComunicazioneUrlType:
      description: Dati inerenti la modifica dell'indirizzo dei documenti di gara'
      type: object
      required: [motivoCorrezione,url]
      additionalProperties: false
      properties:
        motivoCorrezione:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoCorrezioneUrlEnum'    
        url:
          description: Indirizzo dei documenti di gara.
          type: string
          format: url         
    ComunicazioneIDType:
      type: object
      required: [motivoRichiestaModifica]
      additionalProperties: false
      properties:
        motivoRichiestaModifica:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoRichiestaModificaEnum'    
        comunicazioneCUP:
            $ref: '#/components/schemas/ComunicazioneCUPType'
        comunicazioneRibassoAggiudicazione:
            $ref: '#/components/schemas/ComunicazioneRibassoAggiudicazioneType'
        docFAP:
          description: è stato realizzato e autorizzato entro i termini lo studio di fattibilità che esenta dall'uso del BIM
          type: boolean
        comunicazioneUrl:
            $ref: '#/components/schemas/ComunicazioneUrlType'
    AnacFormIDType:
      type: object
      required: [cig,comunicazione]
      additionalProperties: false
      properties:
        cig:
          description: codice identificativo lotto
          type: string 
        comunicazione:
            $ref: '#/components/schemas/ComunicazioneIDType'    
    SchedaIDType:
      description: Scheda  per l'integrazione dei dati non essenziali ai fini della pubblicità legale e del flusso della procedura.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormIDType'