openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD4 - Scheda di adesione AQ/convenzione senza successivo confronto competitivo, senza invio al TED.
  version: 1.0.0
components:
  schemas:
    AggiudicazioneAD4Type:
      type: object
      additionalProperties: false
      required: [afferenteInvestimentiPNRR]
      properties: 
        cig:
          description: codice identificativo lotto
          type: string
          example: 
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string     
        afferenteInvestimentiPNRR:
          description: L’appalto o concessione è afferente gli investimenti pubblici finanziati, in tutto o in parte, con le risorse previste dal PNRR (Piano Nazionale di Ripresa e Resilienza) e/o dal PNC (Piano nazionale per gli investimenti complementari)?
          type: boolean 
        cupLotto:
          description: Cup associati al lotto
          type: array
          items: 
            type: string  
        paritaDiGenereGenerazionale:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ParitaDiGenereGenerazionaleType'
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoType' 
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'          
        finanziamenti:
          description: Dati relativi ai finanziamenti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/FinanziamentoType'           
        aggiudicatari:
          description: Aggiudicatari
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicatarioType'          
        datiBaseAggiudicazioneAppaltoType:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoAD4Type'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'      
    AppaltoAD4Type:
      type: object
      additionalProperties: false
      required: [cig,dataAdesione,relazioneUnicaSulleProcedure,opereUrbanizzazioneScomputo]
      properties:   
        idAppalto:
          description: Codice univoco dell'appalto. il campo viene determinato da anac e restituito nelle response. viene dunque ignorato il valore inserito nelle put/post.
          type: string  
        cig:
          description: CIG relativo all’accordo quadro/convenzione cui si aderisce
          type: string
        dataAdesione: 
          description: Data di adesione all'accordo quadro/convenzione
          type: string
          format: datetime           
        relazioneUnicaSulleProcedure:
          description: Il sottoscritto dichiara che questa SA ha redatto la Relazione Unica sulle Procedure
          type: boolean
        opereUrbanizzazioneScomputo:
          description: Opere di urbanizzazione a scomputo
          type: boolean          
        datiBaseSubappalti:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSubappaltiType'
    AnacFormAD4Type:
      description: Contiene tutti i dati necessari per l'adesione AQ/convenzione senza successivo confronto competitivo, senza invio al TED. 
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false   
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoAD4Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneAD4Type'      
    SchedaAD4Type:
      description: Scheda di adesione AQ/convenzione senza successivo confronto competitivo, senza invio al TED.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormAD4Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'          