openapi: 3.0.0
info:
  title: Modello Dati - Scheda P7_3 - Scheda relativa alla costituzione elenco fornitori.
  version: 1.0.0
components:
  schemas:
    AppaltoP7_3Type:
      description: Oggetto che riporta i dati dell'appalto
      type: object
      additionalProperties: false
      required: [contrattoDifesa,settore,datiBase]
      properties: 
        contrattoDifesa:
          description: Contratto Difesa
          type: boolean
        settore: 
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/SettoreEnum' 
        datiBase:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoPLType'
    LottoP7_3Type:
      description: Oggetto che riporta i dati del lotto
      type: object
      additionalProperties: false
      required: [lotIdentifier,datiBase,datiBaseCPV,datiBaseDocumenti,datiBaseDurata]
      properties:
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante
          type: string      
        datiBase:
          allOf:
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoPLType'
        datiBaseCPV:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'          
        datiBaseDocumenti:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDocumentiType'
        datiBaseDurata:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDurataType'
    AnacFormP7_3Type:
      description: Contiene i dati per la scheda di costituzione elenco fornitori.
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'       
      type: object
      required: [appalto,lotti] 
      additionalProperties: false
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoP7_3Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP7_3Type'    
    SchedaP7_3Type:
      description: Avviso per la costituzione elenco. Articolo 50 comma 1 lettere c) d) e)  decreto legislativo 36/2023. Articolo 3 Allegato II.1. Articolo 31 decreto legislativo  208/2011.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP7_3Type'          