openapi: 3.0.0
info:
  title: Modello Dati - Scheda RSU1 - Scheda di richiesta di subappalto.
  version: 1.0.0
components:
  schemas:
    SoggettoType:
      description: Dati del soggetto
      type: object
      additionalProperties: false
      required: [codiceFiscale,denominazione,ruoloOE,tipoOE,operatoreEstero]
      properties:
        codiceFiscale:
          description: Codice fiscale
          type: string
        denominazione: 
          description: Denominazione
          type: string  
        ruoloOE: 
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/RuoloOEEnum'
        tipoOE: 
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/TipoOEEnum'
        operatoreEstero: 
          type: boolean
        
    OperatoreEconomicoType:
      description: Dati del subappaltatore
      type: object
      additionalProperties: false
      required: [elencoSoggetti,idOE]
      properties:
        idOE: 
          description: id operatore economico
          type: string  
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        elencoSoggetti:
          type: array
          items:
            $ref: '#/components/schemas/SoggettoType'
    ConferenteSubappaltoType:
      description: Dati del conferente
      type: object
      additionalProperties: false
      required: [codiceFiscale,denominazione,ruoloOE,tipoOE,idOE]
      properties:
        idAggiudicatario:
          description: id partecipante dell'aggiudicatario che conferisce il subappalto
          type: string  
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
        idSubappaltanteACascata:
          description: idOE conferente subappalto in caso di subappalto a cascata
          type: string  
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
    SubappaltoType:
      description: Dati relativi ai subappalti
      type: object
      required: [operatoreEconomicoSubappaltatore,conferenteSubappalto,importoPresunto,categoria,cpv]
      additionalProperties: false
      properties:    
        operatoreEconomicoSubappaltatore:
         $ref: '#/components/schemas/OperatoreEconomicoType'
        conferenteSubappalto:
          $ref: '#/components/schemas/ConferenteSubappaltoType'
        oggetto:
          description: Lavoro/Servizio/Fornitura subappalto
          type: string
        oggettoMl:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MultilinguaType'         
        importoPresunto:
          description: Importo presunto Lavoro/ Servizio/Fornitura, subappalto
          type: number
          format: double
        categoria:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum' 
        categoriaScorporabile:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum'          
        cpv:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CPVEnum'   
    AnacFormRSU1Type:
      description: Contiene tutti i dati relativi alla scheda di Richiesta di Subappalto
      type: object
      required: [subappalto,idContratto]
      additionalProperties: false
      properties: 
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
        idSubappalto:
          description: identificativo restituito dal servizio all’invio della scheda di richiesta di subappalto precedente, obbligatorio in caso di subappalto a cascata.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        subappalto:
          $ref: '#/components/schemas/SubappaltoType'
    SchedaRSU1Type:
      description: Comunicazione richiesta di subappalto per qualunque procedura. Articolo 119 decreto legislativo 36/2023
      type: object
      required: [anacForm,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormRSU1Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'            