openapi: 3.0.0
info:
  title: Modello Dati - Scheda PL2_7 - Scheda di pubblicazione per appalti settori ordinari sottosoglia; procedure ordinarie (solo per 1mln <= L< soglia), senza invio al TED.
  version: 1.0.0
components:
  schemas: 
    AppaltoPL2_7Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoPLCompletoType'      
    LottoPL2_7Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoPLCompletoType'      
      type: object
      required: [datiBaseDurata]
      additionalProperties: false
      properties:         
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType'
        datiBaseDurata:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDurataType'          
    AnacFormPL2_7Type:
      description: Contiene tutti i dati necessari per la pubblicazione.
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'
      type: object
      required: [appalto,lotti]
      additionalProperties: false
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoPL2_7Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoPL2_7Type'   
    SchedaPL2_7Type:
      description: Avviso di preinformazione utilizzato per abbreviare i termini per la ricezione delle offerte — settori ordinari. Articolo 50 comma 1 lett. d) decreto legislativo 36/2023. Articolo 81 comma 1 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormPL2_7Type'  