openapi: 3.0.0
info:
  title: Modello Dati - Scheda SO1 - Scheda di sospensione.
  version: 1.0.0
components:
  schemas:
    SospensioneType:
      description: Oggetto che riporta tutti i dati delle Sospensioni
      type: object
      required: [dataVerbSospensione, motivoSospensione, superatoTempo, riserve, verbaleNonSottoscritto]
      additionalProperties: false
      properties:
        codContratto:
          description: identificativo del contratto restituito in response alla scheda di Inizio Lavori.
          type: string      
        dataVerbSospensione: 
          description: Data del verbale di sospensione
          type: string
          format: datetime
        dataVerbRipresa:
          description: Data del verbale di ripresa
          type: string
          format: datetime
        motivoSospensione:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoSospensioneEnum'
        superatoTempo:
          description: E’ stato superato il quarto del tempo contrattuale
          type: boolean   
        riserve:
          description: Iscrizione di riserve dell’appaltatore nei verbali di sospensione e/o ripresa lavori 
          type: boolean   
        verbaleNonSottoscritto:
          description: Verbale/i non sottoscritti dall’appaltatore
          type: boolean
    AnacFormSO1Type:
      description: Contiene tutti i dati relativi alla scheda di Sospensione
      type: object
      required: [sospensioni]
      additionalProperties: false
      properties:
         sospensioni:
          description: Sospensioni
          type: array
          items:
            $ref: '#/components/schemas/SospensioneType'           
    SchedaSO1Type:
      description: Scheda di sospensione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSO1Type'