openapi: 3.0.0
info:
  title: Modello Dati - Scheda SC1 - Scheda di sottoscrizione del contratto
  version: 1.0.0
components:
  schemas:
    DatiContrattoType:
      description: Oggetto che riporta i dati di sottoscrizione del contratto
      type: object
      additionalProperties: false
      required: [importoCauzione,codiceAusa,idPartecipante,cig,dataDecorrenza,dataScadenza, idContratto]
      properties:
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        codiceAusa:
          description: Amministrazione firmataria
          type: array
          items: 
            type: string
        idPartecipante:
          description: id partecipante
          type: string  
        cig:
          description: Lista dei lotti rientranti nel contratto
          type: array
          items: 
            type: string  
        dataStipula:
          description: Data stipula del contratto
          type: string
          format: datetime            
        dataEsecutivita:
          description: Data esecutività del contratto (ove prevista)
          type: string
          format: datetime
        dataDecorrenza:
          description: Data di decorrenza contrattuale
          type: string
          format: datetime 
        dataScadenza:
          description: Data di scadenza contrattuale
          type: string
          format: datetime          
        importoCauzione:
          description: Importo cauzione definitiva in €
          type: string
          format: decimal
    AnacFormSC1Type:
      description: Contiene tutti i dati di sottoscrizione del contratto
      type: object
      additionalProperties: false
      properties:  
        datiContratto:
          $ref: '#/components/schemas/DatiContrattoType'
    SchedaSC1Type:
      description: Scheda di sottoscrizione del contratto
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSC1Type'