openapi: 3.0.0
info:
  title: Modello Dati - Scheda P2_21- Scheda di pubblicazione avviso per un bando di gara sottosoglia.
  version: 1.0.0
components:
  schemas:
    AppaltoP2_21Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP_21Type'     
      type: object
      additionalProperties: false
      required: [datiBase,datiBaseProcedura]
      properties:  
        datiBase:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoType'
        datiBaseProcedura:
          allOf:
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraType'          
        datiBaseStrumentiProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseStrumentiProceduraType'      
    LottoP2_21Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP_21Type'     
      type: object
      additionalProperties: false
      required: [datiBase,datiBaseDocumenti,datiBaseTerminiInvio]
      properties:  
        datiBase:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoType'  
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType'  
        datiBaseCPV:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'  
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoType' 
        datiBaseAggiuntivi:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiuntiviType'        
        datiBaseAggiudicazione:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneOptionalType'  
        datiBaseDocumenti:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDocumentiType'                  
    AnacFormP2_21Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale.
      allOf:  
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      type: object
      additionalProperties: false
      required: [appalto,lotti]
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoP2_21Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP2_21Type'
    SchedaP2_21Type:
      description: Avviso di gara - settori speciali, regime alleggerito. Articolo 50 comma 5 decreto legislativo 36/2023. Libro III decreto legislativo 36/2023.
      type: object
      required: [anacForm,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP2_21Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         
