openapi: 3.0.0
info:
  title: Modello Dati - Scheda NAG2 - Scheda di mancata aggiudicazione della gara - sotto soglia europea
  version: 1.0.0
components:
  schemas:
    AnacFormNAG2Type:
      description: Contiene tutti i dati relativi alla mancata aggiudicazione della gara - sotto soglia europea
      type: object
      additionalProperties: false
      properties:
        datiBaseRisultatoProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseRisultatoProceduraNAGType'
        esitoProceduraNag:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EsitoProceduraNagEnum'
    SchedaNAG2Type:
      description: Scheda di mancata aggiudicazione della gara - sotto soglia europea
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormNAG2Type' 