openapi: 3.0.0
info:
  title: Modello Dati - Scheda PL1_09 - Scheda di pianificazione per appalti settore difesa e sicurezza pari /sopra soglia con invio al TED dell'eform9.
  version: 1.0.0
components:
  schemas:          
    SchedaPL1_09Type:
      description: Scheda di pianificazione per appalti settore difesa e sicurezza pari /sopra soglia con invio al TED dell'eform9.
      type: object
      required: [eform]
      additionalProperties: false
      properties:
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'            
         