openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD5 - Scheda relativa gli appalti di importo inferiore a 5K, senza invio al TED.
  version: 1.0.0
components:
  schemas:
    AggiudicazioneAD5Type:
      type: object
      additionalProperties: false
      required: [lotIdentifier,partecipanti,ccnl,categoria,codIstat,datiBase]
      properties:  
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string               
        cup:
          description: Cup
          type: string  
        partecipanti:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicatarioAD5Type' 
        ccnl:
          description: indicare il codice CNEL o non applicabile
          type: string  
        categoria:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum' 
        categoriaScorporabile:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum'          
        codIstat:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CodIstatEnum' 
        datiBase:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoADType'
        datiBaseCPV:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoADType'    
        datiBaseDocumenti:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDocumentiType'           
    AppaltoAD5Type:
      type: object
      additionalProperties: false
      required: [codiceAppalto,datiBase]
      properties:    
        codiceAppalto:
          description: Identificativo univoco dell'appalto definito dalla Stazione Appaltante
          type: string
          maxLength: 64 
        datiBase:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoADType'           
    AnacFormAD5Type:
      description: Contiene tutti i dati relativi agli appalti di importo inferiore a 5K, senza invio al TED. 
      allOf: # estende la classe AnacFormBaseType
        - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false   
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoAD5Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneAD5Type'      
    SchedaAD5Type:
      description: Affidamento diretto < 5k €. Articolo 49 c. 6 e 50 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormAD5Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'          