openapi: 3.0.0
info:
  title: Modello Dati - Scheda TVR - Comunicazione di Termine Verifiche Requisiti FVOE.
  description: | 
    La scheda TVR (Scheda di Terminazione Verifiche FVOE) è una scheda di comunicazione della terminazione delle verifiche FVOE per mancata prosecuzione della procedura di affidamento a seguito di una preliminare consultazione di mercato.\
    La nuova scheda TVR segue una scheda AVR (scheda di Indagine di Mercato) al termine delle verifiche FVOE quando si decide di non proseguire con la procedura di affidamento e va in uno STATO FINALE.\
    La scheda sarà collegata alla precedente scheda AVR tramite il campo ‘ID scheda’.
  version: 1.0.0
components:
  schemas:
    AnacFormTVRType:
      description: Contiene i dati per la scheda di Terminazione verifiche FVOE.
      type: object
      required: [idSchedaAvr,motivazioneMancatoAffidamento] 
      additionalProperties: false 
      properties:
        idSchedaAvr:
          description: identificativo restituito dal servizio all’invio della scheda AVR.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        motivazioneMancatoAffidamento:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivazioneMancatoAffidamentoEnum'
    SchedaTVRType:
      description: Scheda di Terminazione Verifiche FVOE (TVR).
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormTVRType'
