openapi: 3.0.0
info:
  title: Modello Dati - Scheda C7_3 - Conclusione Elenco Fornitori.
  version: 1.0.0
components:
  schemas:
    AnacFormC7_3Type:
      description: Contiene i dati per la scheda di conclusione dell'elenco fornitori.
      type: object
      required: [idElenco,datiBaseStrumentiProcedura,datiBaseDurata] 
      additionalProperties: false
      properties:
        idElenco:
          description: id restituito dal servizio all'invio della scheda di costituzione elenco fornitori
          type: string  
          format: uuid      
        dataChiusura: 
          description: data di chiusura dell'elenco
          type: string
          format: date-time
    SchedaC7_3Type:
      description: Conclusione Elenco Fornitori.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormC7_3Type'          