openapi: 3.0.0
info:
  title: Modello Dati - Scheda P7_1 - Scheda relativa all'avvio dell'indagine di mercato
  version: 1.0.0
components:
  schemas:
   LottoP7_1Type:
      description: Oggetto che riporta i dati del lotto all'interno della scheda di avvio dell'indagine di mercato
      allOf: # estende la classe LottoP7BaseType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP7BaseType'      
      type: object
      additionalProperties: false
      properties:
        ripetizioniEConsegneComplementari:
          description: L’appalto prevede ripetizioni di servizi/forniture/lavori analoghi e consegne complementari?
          type: boolean 
        opzioniRinnovi:
          description: L’appalto prevede opzioni/rinnovi?
          type: boolean 
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoType'          
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseTerminiInvioSoloScadenzaType'
   AnacFormP7_1Type:
      description: Contiene i dati per la scheda di avvio dell'indagine di mercato
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'   
      type: object
      required: [appalto,lotti] 
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP7BaseType'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP7_1Type'    
   SchedaP7_1Type:
      description: Scheda relativa all'avvio dell'indagine di mercato.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP7_1Type'          