openapi: 3.0.0
info:
  title: Modello Dati - Scheda I1 - Scheda di inizio prestazione
  version: 1.0.0
components:
  schemas:
    DatiInizioType:
      description: Oggetto che riporta i dati di inizio prestazione
      type: object
      additionalProperties: false
      required: [importoCauzione,consegnaFrazionata,avvioPerFasi,consegnaSottoRiserva,dataEffettivoInizio,dataFinePrevista]
      properties:
        dataStipula:
          description: Data stipula del contratto
          type: string
          format: datetime
        dataEsecutivita:
          description: Data esecutività del contratto (ove prevista)
          type: string
          format: datetime
        importoCauzione:
          description: Importo cauzione definitiva in €
          type: string
          format: decimal
        dataDisposizioneInzio:
          description: Data disposizione dell’inizio della prog. Esecutiva
          type: string
          format: datetime
        dataApprovazione:
          description: Data approvazione del  progetto Esecutivo
          type: string
          format: datetime  
        consegnaFrazionata:
          description: Consegna frazionata
          type: boolean
        avvioPerFasi:
          description: L'avvio dell'esecuzione del contratto e' per fasi
          type: boolean
        dataVerbalePrimaConsegna:
          description: Data verbale prima consegna lavori
          type: string
          format: datetime
        dataVerbaleAvvioPrimaFase:
          description: Data verbale di avvio della prima fase dell'esecuzione del contratto
          type: string
          format: datetime
        dataVerbaleConsegnaDefinitiva:
          description: Data verbale consegna definitiva
          type: string
          format: datetime
        consegnaSottoRiserva?:
          description: Consegna sotto riserva di legge?
          type: boolean
        dataEffettivoInizio:
          description: Data di effettivo inizio lavori/servizi/forniture (consegna completa/avvio di tutte le prestazioni del contratto)
          type: string
          format: datetime
        dataFinePrevista:
          description: Data fine prevista per dare ultimazione ai lavori/servizi/forniture 
          type: string
          format: datetime
    AnacFormI1Type:
      description: Contiene tutti i dati di inizio prestazione
      type: object
      additionalProperties: false
      properties:  
        datiInizio:
          $ref: '#/components/schemas/DatiInizioType'
    SchedaI1Type:
      description: Scheda di inizio esecuzione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormI1Type'