openapi: 3.0.0
info:
  title: Modello Dati - Scheda P7_3 - Scheda relativa alla costituzione elenco fornitori sottosoglia.
  version: 1.0.0
components:
  schemas:
    AppaltoP7_3Type:
      description: Oggetto che riporta i dati dell'appalto
      type: object
      additionalProperties: false
      properties:
        idAppalto:
          description: Codice univoco dell'appalto.il campo viene determinato da anac e restituito nelle response. viene dunque ignorato il valore inserito nelle put/post.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"          
        datiBase:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoPLType'
          required: [oggetto]
    LottoP7_3Type:
      description: Oggetto che riporta i dati del lotto all'interno della scheda di costituzione elenco fornitori sottosoglia.
      type: object
      additionalProperties: false
      required: [lotIdentifier]
      properties:
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante
          type: string      
        datiBase:
          allOf:
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoPLType'
          required: [oggetto,oggettoContratto]  
        datiBaseCPV:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'
          required: [cpvPrevalente,cpvSecondarie]          
        datiBaseDocumenti:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDocumentiType'
        datiBaseDurata:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDurataType'
    AnacFormP7_3Type:
      description: Contiene i dati per la scheda di costituzione elenco fornitori.
      type: object
      required: [appalto,lotti] 
      additionalProperties: false
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoP7_3Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP7_3Type'    
    SchedaP7_3Type:
      description: Scheda relativa alla costituzione elenco fornitori.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP7_3Type'          