openapi: 3.0.0
info:
  title: Modello Dati - Scheda A1.37 - Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso sui risultati di un concorso di progettazione — direttiva settoriale, progettazione. Articolo 96, paragrafo 1, secondo comma, della direttiva 2014/25/UE con invio di eform37. 
  version: 1.0.0
components:
  schemas:
    AggiudicatarioA1.37Type:
      description: Dati dell'aggiudicatario
      allOf: # estende la classe AggiudicatarioType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicatarioType'      
      type: object
      required: [importoAggiudicazioneAffidamento]
      additionalProperties: false
      properties:
        importoAggiudicazioneAffidamento:
          description: Importo di aggiudicazione/affidamento 
          type: string
          format: decimal 
    AnacFormA1.37Type:
      description: Contiene tutti i dati relativi all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso sui risultati di un concorso di progettazione — direttiva settoriale, progettazione. Articolo 96, paragrafo 1, secondo comma, della direttiva 2014/25/UE
      type: object
      required: [aggiudicatari]
      additionalProperties: false
      properties:
        aggiudicatari:
          description: Dati degli aggiudicatari
          type: array
          items: 
            $ref: '#/components/schemas/AggiudicatarioA1.37Type'  
    SchedaA1.37Type:
      description: Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso sui risultati di un concorso di progettazione — direttiva settoriale, progettazione. Articolo 96, paragrafo 1, secondo comma, della direttiva 2014/25/UE con invio di eform37.
      type: object
      required: [anacFormA1, eform]
      additionalProperties: false
      properties:
        anacFormA1:
          $ref: '#/components/schemas/AnacFormA1.37Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'          